apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox
resources:
- manifest.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: oteltest-collector-conf
  files:
  - collector.yaml
